### ISSUE TITLE
gabisa login

### ISSUE THREAD

**Issue by renzhaxor** [riedayme/FacebookKit#1]
sebelum update dulunya work bisa login. skrg gabisa login via user pw respinnya access token empty. login via cokie. responnya cokie die pdhl baru buat

**Comment by riedayme** [comment]
akun mas kena tinjau kayaknya saya masih work ini hihihi :D cb buka url ini trs cari tulisan "EAAAA" ada ga ? 

https://m.facebook.com/composer/ocelot/async_loader/?publisher=feed

**Comment by renzhaxor** [comment]
siap

**Comment by renzhaxor** [comment]
ga ada mas. iya kena tinjau emg. gbsa ya mas :3

**Comment by renzhaxor** [comment]
sama gw jg gitu, fb baru pdhl udh semingguan lebih udh buat ngebot jg
